name: t_jwt
description: A simple library for signing and verifying JWTs in Dart lang.
version: 1.0.0
repository: https://github.com/akula-shark/t-jwt
issue_tracker: https://github.com/akula-shark/t-jwt/issues

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

platforms:
  windows:
  macos:
  linux:
